version: '3.8'

services:
    # PHP service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        ports:
            - "8082:80"
        networks:
            - my_network

    # MySQL service
    mysql:
        image: mysql:8.0
        container_name: mysql-container
        environment:
            MYSQL_ROOT_PASSWORD: secure
            MYSQL_DATABASE: boilerplate
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - my_network

    # phpMyAdmin service
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin-container
        environment:
            PMA_HOST: mysql-container
            PMA_PORT: 3306
        ports:
            - "8081:80"
        depends_on:
            - mysql
        networks:
            - my_network

networks:
    my_network:
        external: true

volumes:
    mysql_data:
